### ISSUE TITLE
Upgrade to a different javascript protobuf decoder

### ISSUE THREAD

**Issue by Jragonmiris** [SCAII/SCAII#13]
The current one is leading to numerous precisions issues (#8, possibly #10) it may be worth it for @jedirv to upgrade to a different protobuf library that respects at least integer types instead of converting into Number.

**Comment by jedirv** [comment]
I can see how the big integers we had in play would suffer from precision issues.  Javascript has a constant called Number.MAX_SAFE_INT which is shown here compared to the big numbers we had before:

9007199254740991     <---Number.MAX_SAFE_INT
7459425232328277000
7459425232328276992

It might be because I haven't had to do much numerical programming so don't keep a constant grip on the numerical representation nuances, but I can't see how a precision issue might be at the root of causing a number like 1.202095961574872 to be misconstrued as 0.1  (the latest mismatch I'm seeing, after rebasing in the change this morning) ,especially when lots of numbers are flowing back and forth that look like that and are being handled correctly (by the test checker).  Intuitively, to me, it seems more likely that its a book-keeping error that happens when values are changed at the tester - it never happens on the initial viz packet response, and doesn't happen in following packets as longs as values aren't being changed - it only happens after a value is adjusted in the tester.  There isn't any math happening on my end - I'm just replacing values with whatever values are present.    Thoughts?

As far as switching libraries, I only found one other protobuf library (protobuf.js) but it had at least one issue that would require modifying the library to get it to work with our websocket.  I was thinking that google's compiler would be the safest (most tested) of the lot, since protocol buffers are their creation.

**Comment by jedirv** [comment]
I'll see if I can figure out how to add a toJson() call on the objects you are putting on the wire and logging them to a file as another data point.

**Comment by Jragonmiris** [comment]
Did you make sure to rerun `protoc` on the protobuf update? I normalized it to use doubles everywhere.

**Comment by Jragonmiris** [comment]
I found this:

https://github.com/dcodeIO/ProtoBuf.js/

Is this the one you meant? I see it has a `--force-long` which you can use with a library called long.js to require int64s to be in a type that maintains precision.

**Comment by jedirv** [comment]
Yes, I reran and did a diff and saw the doubles handling was new.

https://github.com/dcodeIO/ProtoBuf.js/ was the one I looked at - I'll take another look now that I know more, though.

**Comment by jedirv** [comment]
Obsolete(-ish) we'll just advise people to not use ints above MaxSafeInt
