### ISSUE TITLE
Add replay executable target to core

### ISSUE THREAD

**Issue by LinearZoetrope** [SCAII/SCAII#18]
Once we have the core recording replays (#17), we need to be able to play them. I think the easiest way of doing this is with a binary that takes a replay file and runs it, with a flag (or config file) specifying if we also want a visualization controller (#16).

**Comment by jedirv** [comment]
Reviewing this note from yesterday's architectural discussion:

How replay info is persisted -
	Agent forwards backend config to recorder + recorder sends initial NON-DIVERGING (aka random seed saved) serialization request to backend
	Agent sends copy of action to recorder at each state
	every n states, recorder sends NON-DIVERGING serialization request to backend 

... My intuition kept nagging at me that the game itself should be persisting info, but maybe I can put that to rest -  I guess it's the case that the Agent will be aware of not only all of its actions, but also all of the opposing players actions since they will have to be sent to the Agent in order for the Agent to react.  Thus, all the persistence can be driven from the agent just as easily as from inside the game, as all the events are known in order at both places.  True?

**Comment by Jragonmiris** [comment]
It's in core, not the agent.

**Comment by jedirv** [comment]
If you mean recorder is in core, I see that, but it looks like that note (unless I notated incorrectly) indicates that the Agent is telling the recorder when to record (and what to record). Is that not the case?  If not, which component is sending actions to the recorder - it needs to be a component that knows the actions that both players are performing.  I'm thinking router is not smart enough to know inner semantics of messages. Or is recorder getting a copy of all messages and just picking out the ones that involve actions?

**Comment by Jragonmiris** [comment]
For now, the other player's actions are based off the internal game and thus deterministic wrt to the non-diverging state.. We're not supporting multiple players needing to be recorded per frame, but if we were all that would need to happen is that each agent would need to individually register with the recorder and it would finish recording after it receives an action from every player.

**Comment by jedirv** [comment]
So for our simple two player case, which component originates the message that is sent to the recorder that says "nonAgent player did actionx"?  Is it the backend?

**Comment by Jragonmiris** [comment]
Nobody would. We only need to record Agent actions.

**Comment by jedirv** [comment]
I finally get it - since things are non-diverging, all the other players moves will be the deterministic.  I had thought we were saving keyframes and then stepping the game forward from both sides using both sides recorded moves.   But with the approach of just using the agent moves, we can just use the game as is and each game doesn't need any "I'm replayable" logic to handle external control for the inner player.   

Mightn't there be some backend at some point that doesn't have that guarantee? Is that guarantee "Alan-blessed"?

Also, does that non-divergence guarantee apply to the case where we have two competing external Agents playing (one as Agent and one as module)?

**Comment by Jragonmiris** [comment]
Yes, the guarantee still applies. In the case where a backend can't guarantee its agents actions are non-divergent I suppose we could have the backend manually register its built-in agent as if it were a real agent.

If a backend can't do a non-diverging serialization I don't know how we'd do a recording except for doing a keyframe every state (at which point recording actions becomes superfluous).

**Comment by jedirv** [comment]
Think this is done but will leave open until I test replay after Zoe adjust RTS to work with recorder.
