### ISSUE TITLE
Add basic installation tool

### ISSUE THREAD

**Issue by LinearZoetrope** [SCAII/SCAII#19]
Since we have environments in different repositories than core, it would be nice to have a basic installation tool.

This would:

* Create a `.scaii` directory in the user's home
* Put any language glue in a `.scaii/python` (`.scaii/lua` etc) folder
* Put any core libraries in `.scaii/core` folder
* Put any core executables (e.g. replay) in a `.scaii/bin` folder
* Put any game wrappers in a language folder (e.g. `.scaii/python/env_name/...`)
* Put any game backends in a `backend/core` and `backend/bin` (for RPC backends) folder
* Fetch any big dependencies that are needed (e.g. `protoc`, `closure-library` etc) with user permission
* Add relevant things to `PYTHONPATH`, `PATH`, etc with user permission.

I'd recommend having something like

* `scaii install core`
* `scaii install core local <path>`
* `scaii install env <name or github URL>`
* `scaii install env all` (installs all known/official backends)
* `scaii install env local <path>` (installs an environment from a path rather than a URL)

More can be added later, but this is what we need. For now, we can clone from git but in the future we'd like to support pulling prebuilt assets from any releases we make.

This will help **immensely** with CI and integration testing environments, since from a backend we know we can fetch the tool and call

1. `scaii install core`
2. `scaii install local env .`
3. **run tests**

And when testing core we can do:

1. `scaii install core local .`
2. `scaii install env all`
3. **run tests**

I think it would be nice to do this in Rust and base it off Cargo. Rust has benefits over other options. Rust we can compile to native, so we don't need to expect people to have python, and it's platform agnostic so we don't need to maintain a shell, batch, and powershell file or anything.

**Comment by Jragonmiris** [comment]
Note: https://github.com/docopt/docopt.rs might be helpful here

**Comment by LinearZoetrope** [comment]
@jedirv I'm moving this up in priority a little bit because of the difficulty in getting new people set up. The explanation stuff is still by far more important, but I'm convinced this is an issue now.

**Comment by jedirv** [comment]
later:
scaii viz  // opens the UI in browser
scaii replay  // opens the browser and runs default replay file

install yes/no protoc question during install

To start just do the stuff in rust that you would need to do by hand after pulling from github.

**Comment by jedirv** [comment]
Tried using the git2 crate only to hit a very annoying error.  There's a build script in that or a dependency that doesn't handle pathnames with spaces in them. So it choke on this line:

C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.10.25017\bin\HostX86\x64\CL.exe /c /IC:\Users\Jed /Zi /nologo /W1 /WX- /diagnostics:classic /Od /Ob0 /D GIT_SSH /D "CMAKE_INTDIR=\"Debug\"" /D _MBCS /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_a9ee4.dir\Debug\\" /Fd"cmTC_a9ee4.dir\Debug\vc141.pdb" /Gd /TC /errorReport:queue  /GL- Irvine\exact\SCAII\target\debug\build\libssh2-sys-aeea67b1023231b1\out/include "C:\Users\Jed Irvine\exact\SCAII\target\debug\build\libgit2-sys-3faccc8d26cd11e5\out\build\CMakeFiles\CMakeTmp\testCCompiler.c"

Note the /IC:\Users\Jed    followed by a bunch of stuff and then between the /GL and the .c file lands the remainder of the path !  :   Irvine\exact\....   

I considered repositioning my git installation under a folder that doesn't have a space in it, but then if some other person's machine had the same issue, then our installation tool wouldn't work.  So, for now, I'll shell out to git. Grrr- it looked like it was going to be a four line function to get the clone.

**Comment by LinearZoetrope** [comment]
Let's look at it tomorrow

**Comment by jedirv** [comment]
Not sure if I mis-interpreted the issue in the above comment or if this is a distinct issue.  What I think is going on is the following.

On unix, running a command like 

%ls *.foo

... works fine, but quoting it like this...

%ls "*.foo"

...foils the expansion.  On Windows, however, the expansion is not foiled.  I believe that the rust's Command is emitting the args with quotes around them, perhaps in anticipation of potential spaces in paths.  So when it does this on Windows, it works:

(i.e. from println!("...running command {:?}", c); )...

...running command "cmd" "/C" "C:\\Users\\Jed Irvine\\.scaii\\protoc\\bin\\protoc.exe" "--proto_path=./../../common_protos" "--js_out=library=vizProto,binary:." "./../../common_protos/*.proto"

...but on Mac I get the misleading error message that has the quotes stripped:

./../../common_protos/*.proto: No such file or directory

When I change the arg to just have cfg.proto rather than *.proto, it works, giving me confidence that this is the issue.

I'm out of time to work on this before heading out on trip, so I'm just going to push what I have and let you decide if you want to generate a pull request with just the windows side working (if the student is using windows then might be worth it.)

**Comment by jedirv** [comment]
after thought - I left a bunch of commented out debugging lines in the run_command_on_mac function as I expect I'll need them for more troubleshooting, in case you get to clippy that stuff.  Ugh.

**Comment by LinearZoetrope** [comment]
Not finished, but closing because we now have SCAII/Sky-install
